# Generated by Django 5.0.4 on 2024-05-08 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_module', '0011_alter_user_is_servicer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=300, verbose_name='نوع خدمات')),
                ('description', models.TextField(db_index=True, verbose_name='توضیحات')),
                ('price', models.IntegerField(blank=True, verbose_name='هزینه')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('service_date', models.DateTimeField(verbose_name='تاریخ انجام پروژه')),
                ('address', models.TextField(db_index=True, verbose_name='محل انجام خدمات')),
                ('service_time', models.IntegerField(verbose_name='ساعت خدمت')),
                ('is_submit', models.BooleanField(default=False, verbose_name='قبول شده / نشده')),
                ('servicer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account_module.servicer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
