# Generated by Django 5.0.4 on 2024-05-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='جنسیت خدمات دهنده'),
        ),
    ]
