# Generated by Django 5.0.4 on 2024-05-09 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_module', '0003_remove_service_address_alter_service_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 5, 9), verbose_name='ساعت خدمت'),
            preserve_default=False,
        ),
    ]
