# Generated by Django 5.0.4 on 2024-05-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_module', '0005_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
    ]
