# Generated by Django 5.0.4 on 2024-05-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request_module', '0006_alter_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.AddField(
            model_name='service',
            name='serviceid',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
