# Generated by Django 5.0.2 on 2024-05-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_module', '0002_alter_comment_service_alter_comment_servicer'),
        ('user_request_module', '0008_service_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_service_comment', to='user_panel_module.comment'),
        ),
    ]
