# Generated by Django 5.0.4 on 2024-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_servicer',
            field=models.CharField(default=False, max_length=100, verbose_name='خدمات دهنده'),
        ),
    ]
