# Generated by Django 5.0.4 on 2024-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_alter_user_is_servicer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='استان و شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_number',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='شماره ملی'),
        ),
    ]
