# Generated by Django 5.0.4 on 2024-05-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_request_module', '0007_remove_service_slug_service_serviceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداخت')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_request_module.service')),
            ],
        ),
    ]
