# Generated by Django 5.0.4 on 2024-05-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده ؟'),
        ),
    ]
