# Generated by Django 5.0.2 on 2024-05-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_module', '0001_initial'),
        ('user_request_module', '0008_service_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by_user', to='user_request_module.service'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='servicer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by_servicer', to='user_request_module.service'),
        ),
    ]
