# Generated by Django 5.0.2 on 2024-05-24 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel_module', '0002_alter_comment_service_alter_comment_servicer'),
        ('user_request_module', '0009_service_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='comment_by_user', to='user_request_module.service'),
        ),
    ]
